// Fachada de @babylonjs/core: solo lo que el juego usa, por rutas profundas (cada módulo trae sus propios efectos de registro).
// El import `* as B from "@babylonjs/core"` está desviado acá (vite.config.ts y tsconfig.json): el índice completo del paquete metía ~4 MB de código
// que se parsea y evalúa antes de dibujar la portada. Si el código usa un B.Algo nuevo, tsc lo marca: agregarlo abajo (misma ruta que en node_modules/@babylonjs/core).
export { AbstractEngine } from "@babylonjs/core/Engines/abstractEngine.js";
export { AbstractMesh } from "@babylonjs/core/Meshes/abstractMesh.js";
export { AnimationGroup } from "@babylonjs/core/Animations/animationGroup.js";
export { Axis } from "@babylonjs/core/Maths/math.axis.js";
export { BakedVertexAnimationManager } from "@babylonjs/core/BakedVertexAnimation/bakedVertexAnimationManager.js";
export { BaseTexture } from "@babylonjs/core/Materials/Textures/baseTexture.js";
export { Camera } from "@babylonjs/core/Cameras/camera.js";
export { CascadedShadowGenerator } from "@babylonjs/core/Lights/Shadows/cascadedShadowGenerator.js";
export { Color3 } from "@babylonjs/core/Maths/math.color.js";
export { Color4 } from "@babylonjs/core/Maths/math.color.js";
export { ColorCurves } from "@babylonjs/core/Materials/colorCurves.js";
export { Constants } from "@babylonjs/core/Engines/constants.js";
export { DefaultRenderingPipeline } from "@babylonjs/core/PostProcesses/RenderPipeline/Pipelines/defaultRenderingPipeline.js";
export { DepthOfFieldEffectBlurLevel } from "@babylonjs/core/PostProcesses/depthOfFieldEffect.js";
export { DirectionalLight } from "@babylonjs/core/Lights/directionalLight.js";
export { DynamicTexture } from "@babylonjs/core/Materials/Textures/dynamicTexture.js";
export { Engine } from "@babylonjs/core/Engines/engine.js";
export { FSR1RenderingPipeline } from "@babylonjs/core/PostProcesses/RenderPipeline/Pipelines/fsr1RenderingPipeline.js";
export { FxaaPostProcess } from "@babylonjs/core/PostProcesses/fxaaPostProcess.js";
export { FreeCamera } from "@babylonjs/core/Cameras/freeCamera.js";
export { GlowLayer } from "@babylonjs/core/Layers/glowLayer.js";
export { HavokPlugin } from "@babylonjs/core/Physics/v2/Plugins/havokPlugin.js";
export { HemisphericLight } from "@babylonjs/core/Lights/hemisphericLight.js";
export { ImageProcessingConfiguration } from "@babylonjs/core/Materials/imageProcessingConfiguration.js";
export { InstancedMesh } from "@babylonjs/core/Meshes/instancedMesh.js";
export { Light } from "@babylonjs/core/Lights/light.js";
export { LinesMesh } from "@babylonjs/core/Meshes/linesMesh.js";
export { LoadAssetContainerAsync } from "@babylonjs/core/Loading/sceneLoader.js";
export { Material } from "@babylonjs/core/Materials/material.js";
export { MaterialDefines } from "@babylonjs/core/Materials/materialDefines.js";
export { MaterialPluginBase } from "@babylonjs/core/Materials/materialPluginBase.js";
export { Matrix } from "@babylonjs/core/Maths/math.vector.js";
export { Mesh } from "@babylonjs/core/Meshes/mesh.js";
export { MeshBuilder } from "@babylonjs/core/Meshes/meshBuilder.js";
export { MultiMaterial } from "@babylonjs/core/Materials/multiMaterial.js";
export { Observer } from "@babylonjs/core/Misc/observable.js";
export { PBRMaterial } from "@babylonjs/core/Materials/PBR/pbrMaterial.js";
export { ParticleSystem } from "@babylonjs/core/Particles/particleSystem.js";
export { PhysicsAggregate } from "@babylonjs/core/Physics/v2/physicsAggregate.js";
export { PhysicsBody } from "@babylonjs/core/Physics/v2/physicsBody.js";
export { PhysicsMotionType } from "@babylonjs/core/Physics/v2/IPhysicsEnginePlugin.js";
export { PhysicsRaycastResult } from "@babylonjs/core/Physics/physicsRaycastResult.js";
export { PhysicsShapeType } from "@babylonjs/core/Physics/v2/IPhysicsEnginePlugin.js";
export { PointLight } from "@babylonjs/core/Lights/pointLight.js";
export { Quaternion } from "@babylonjs/core/Maths/math.vector.js";
export { Ray } from "@babylonjs/core/Culling/ray.core.js";
export { ReflectionProbe } from "@babylonjs/core/Probes/reflectionProbe.js";
export { RenderTargetTexture } from "@babylonjs/core/Materials/Textures/renderTargetTexture.js";
export { Scalar } from "@babylonjs/core/Maths/math.scalar.js";
export { Scene } from "@babylonjs/core/scene.js";
export { ShadowGenerator } from "@babylonjs/core/Lights/Shadows/shadowGenerator.js";
export { SpotLight } from "@babylonjs/core/Lights/spotLight.js";
export { StandardMaterial } from "@babylonjs/core/Materials/standardMaterial.js";
export { SubMesh } from "@babylonjs/core/Meshes/subMesh.js";
export { Texture } from "@babylonjs/core/Materials/Textures/texture.js";
export { TransformNode } from "@babylonjs/core/Meshes/transformNode.js";
export { UniformBuffer } from "@babylonjs/core/Materials/uniformBuffer.js";
export { Vector3 } from "@babylonjs/core/Maths/math.vector.js";
export { Vector4 } from "@babylonjs/core/Maths/math.vector.js";
export { VertexAnimationBaker } from "@babylonjs/core/BakedVertexAnimation/vertexAnimationBaker.js";
export { VertexBuffer } from "@babylonjs/core/Buffers/buffer.js";
export { VertexData } from "@babylonjs/core/Meshes/mesh.vertexData.js";
export { Viewport } from "@babylonjs/core/Maths/math.viewport.js";
export type { Nullable } from "@babylonjs/core/types.js";
export type { PhysicsAggregateParameters } from "@babylonjs/core/Physics/v2/physicsAggregate.js";
export type { PhysicsEngine as PhysicsEngineV2 } from "@babylonjs/core/Physics/v2/physicsEngine.js";
// Efectos de registro que el índice completo traía solos y las rutas profundas no (cada uno agrega métodos a Scene o al motor)
import "@babylonjs/core/Physics/physicsEngineComponent.js";
import "@babylonjs/core/Physics/v2/physicsEngineComponent.js";
